### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by ZqinKing** [breeze303/openwrt-6.x#14]
Building backport-include/backport/autoconf.h ... done.
  CC [M]  /home/zqinking/ax1800pro/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/mac80211-regular/backports-6.6.15/drivers/net/wireless/ath/ath11k/core.o
In file included from /home/zqinking/ax1800pro/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/mac80211-regular/backports-6.6.15/drivers/net/wireless/ath/ath11k/core.h:33,
                 from /home/zqinking/ax1800pro/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/mac80211-regular/backports-6.6.15/drivers/net/wireless/ath/ath11k/core.c:13:
/home/zqinking/ax1800pro/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/mac80211-regular/backports-6.6.15/drivers/net/wireless/ath/ath11k/nss.h:11:10: fatal error: nss_api_if.h: No such file or directory
   11 | #include <nss_api_if.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[11]: *** [scripts/Makefile.build:243: /home/zqinking/ax1800pro/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/mac80211-regular/backports-6.6.15/drivers/net/wireless/ath/ath11k/core.o] Error 1
make[10]: *** [scripts/Makefile.build:480: /home/zqinking/ax1800pro/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/mac80211-regular/backports-6.6.15/drivers/net/wireless/ath/ath11k] Error 2
make[9]: *** [scripts/Makefile.build:480: /home/zqinking/ax1800pro/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/mac80211-regular/backports-6.6.15/drivers/net/wireless/ath] Error 2
make[8]: *** [scripts/Makefile.build:480: /home/zqinking/ax1800pro/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/mac80211-regular/backports-6.6.15/drivers/net/wireless] Error 2
make[7]: *** [Makefile:1913: /home/zqinking/ax1800pro/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/mac80211-regular/backports-6.6.15] Error 2
make[6]: *** [Makefile.build:13: modules] Error 2
make[5]: *** [Makefile.real:105: modules] Error 2
make[4]: *** [Makefile:121: modules] Error 2
make[4]: Leaving directory '/home/zqinking/ax1800pro/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/mac80211-regular/backports-6.6.15'
make[3]: *** [Makefile:448: /home/zqinking/ax1800pro/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/mac80211-regular/backports-6.6.15/.built] Error 2
make[3]: Leaving directory '/home/zqinking/ax1800pro/openwrt/package/kernel/mac80211'
time: package/kernel/mac80211/regular/compile#1.15#0.23#1.35
    ERROR: package/kernel/mac80211 failed to build (build variant: regular).
make[2]: *** [package/Makefile:173: package/kernel/mac80211/compile] Error 1
make[2]: Leaving directory '/home/zqinking/ax1800pro/openwrt'
make[1]: *** [package/Makefile:167: /home/zqinking/ax1800pro/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/zqinking/ax1800pro/openwrt'
make: *** [/home/zqinking/ax1800pro/openwrt/include/toplevel.mk:233: world] Error 2

**Comment by ZqinKing** [comment]
> 确定使用了本项目的完整代码嘛？可否发一份.config文件看看

使用的是B大，https://github.com/breeze303/OpenWrt-CI项目中的config-all进行编译。
[config.txt](https://github.com/user-attachments/files/15796273/config.txt)

**Comment by King-Of-Knights** [comment]
简单看了一下，似乎你没有选择要编译的目标设备，尝试修改以下代码，设置一个目标设备吧：
```
CONFIG_TARGET_qualcommax_ipq60xx=y
CONFIG_TARGET_MULTI_PROFILE=y
# CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_8devices_mango-dvk is not set
# CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_glinet_gl-ax1800 is not set
# CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_glinet_gl-axt1800 is not set
# CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_jdc_ax1800-pro is not set
# CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_netgear_wax214 is not set
# CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_redmi_ax5 is not set
# CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_redmi_ax5-jdcloud is not set
# CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_xiaomi_ax1800 is not set
# CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_qihoo_v6 is not set
# CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_cmiot_ax18 is not set
# CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_zn_m2 is not set
# CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_yuncore_fap650 is not set
```

**Comment by breeze303** [comment]
确认下你的库有没有拉错或者没更新

**Comment by ZqinKing** [comment]
> 确认下你的库有没有拉错或者没更新

还真是，没仔细看，竟然没选设备。。。

**Comment by King-Of-Knights** [comment]
> > 确认下你的库有没有拉错或者没更新
> 
> 还真是，没仔细看，竟然没选设备。。。

云编译应该是没有问题的，选择设备再编译一下，如果没有问题，close 这个issue吧

**Comment by ZqinKing** [comment]
> > > 确认下你的库有没有拉错或者没更新
> > 
> > 
> > 还真是，没仔细看，竟然没选设备。。。
> 
> 云编译应该是没有问题的，选择设备再编译一下，如果没有问题，close 这个issue吧

嗯好的。
