### ISSUE TITLE
编译ax5   passwall不管用

### ISSUE THREAD

**Issue by abaibubaix** [breeze303/openwrt-6.x#16]
编译ax5 passwall不管用 应用玩节点 测试百度谷歌git都失败 电脑没网

**Comment by abaibubaix** [comment]
编译ax5 passwall不管用  应用玩节点  测试百度谷歌git都失败 电脑没网

**Comment by sendlan** [comment]
插件的原因，建议试试passwall2

**Comment by King-Of-Knights** [comment]
这个是passwall的问题，非本项目问题，建议看看是否装了mwan3，如果装了，删去试试
