### ISSUE TITLE
passwall有问题，开远程dns没网

### ISSUE THREAD

**Issue by abaibubaix** [breeze303/openwrt-6.x#17]
不管是哪个版本的passwall，只要下面选远程dns，浏览器就没网了，微信qq这些软件还有网，这个bug目前来看只有ax5机型有
![20240615195942](https://github.com/breeze303/openwrt-6.x/assets/74819180/e242f949-3c4b-4cf3-8dcb-20a66b60a9f3)

**Comment by breeze303** [comment]
看日志，你应该去passwall下反馈这个问题
