### ISSUE TITLE
no wifi 的M2 安装 zerotier缺少依赖无法安装

### ISSUE THREAD

**Issue by 294098372** [breeze303/openwrt-6.x#2]
### Describe the bug

依赖的软件包 libstdcpp6 在所有仓库都未提供

### OpenWrt version

6.6.2

### OpenWrt release

R2024-05-06 03:44:22 for IPQ60XX

### OpenWrt target/subtarget

R2024-05-06 03:44:22 for IPQ60XX

### Device

M2

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by breeze303** [comment]
这不属于源码问题请，自行更改编译配置文件
