### ISSUE TITLE
淅 bug

### ISSUE THREAD

**Issue by czghzh** [breeze303/openwrt-6.x#3]
使用你的源码编译后，luci-app-turboacc编译进去但使用不生效，docker创建macvlan不生效。
换成这个编译 https://github.com/JiaY-shi/openwrt/tree/ipq60xx-devel_nss，上面的问题就正常

**Comment by breeze303** [comment]
补丁问题，有空我修修

**Comment by czghzh** [comment]
> 补丁问题，有空我修修
忘记说了，我编译的是京东云 jdc ax1800pro

**Comment by breeze303** [comment]
你的插件用的是lean的还是别的turboacc插件

**Comment by czghzh** [comment]
> 你的插件用的是lede的还是别的turboacc插件
你好感谢你的跟进，我使用的是这个里面的
https://github.com/kiddin9/openwrt-packages
