### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by czghzh** [breeze303/openwrt-6.x#4]
感谢您的出色源码，
但现在编译出来的固件默认没有打开wifi,修改：
https://github.com/breeze303/openwrt-6.x/blob/main/package/network/config/wifi-scripts/files/lib/wifi/mac80211.sh
里面的：
set wireless.${name}.disabled=1
为：
set wireless.${name}.disabled=0
这样编译出来的固件默认就打开wifi的

**Comment by breeze303** [comment]
ok
