### ISSUE TITLE
JDCloud AX1800 Pro编译出来的dhcp客户端无法获取上层ip，设置静态也无法上网。

### ISSUE THREAD

**Issue by zlxyc** [breeze303/openwrt-6.x#7]
JDCloud AX1800 Pro 编译出来的dhcp客户端无法获取上层ip，设置静态也无法上网。

这里是日志

[系统日志.txt](https://github.com/JiaY-shi/openwrt/files/15345970/default.txt)

[内核日志.txt](https://github.com/JiaY-shi/openwrt/files/15345973/default.txt)

**Comment by czghzh** [comment]
是的我以前编译时没这问题，但昨天编译出来的固件出现了你同样的问题，可能最近的源码有问题，等breeze303大佬修复吧

**Comment by zlxyc** [comment]
> 是的我以前编译时没这问题，但昨天编译出来的固件出现了你同样的问题，可能最近的源码有问题，等breeze303大佬修复吧

在JiaY-shi大佬那里看在了修复方式，并验证可用。在dts文件中switch节点中增加 switch_mac_mode = <MAC_MODE_PSGMII>

**Comment by breeze303** [comment]
已修复
