### ISSUE TITLE
本地编译feeds的依赖找不到

### ISSUE THREAD

**Issue by f1owkang** [breeze303/openwrt-6.x#8]
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a dependency on 'libpcre', which does not exist

多次尝试无果，直接进行编译报错

**Comment by f1owkang** [comment]
修改文件有帮助，不再提示 "package/feeds/telephony/freeswitch/Makefile"
line 323:
+libpcre \ ----> +libpcre2 \

**Comment by breeze303** [comment]
那是上游软件源问题，暂时只能本地修改

**Comment by f1owkang** [comment]
> 那是上游软件源问题，暂时只能本地修改

感谢回复，我编译的时候观察到似乎软件包有缺失，例如在lede中有luci-app-arpbind，但在本项目中没有发现

**Comment by breeze303** [comment]
> > 那是上游软件源问题，暂时只能本地修改
> 
> 感谢回复，我编译的时候观察到似乎软件包有缺失，例如在lede中有luci-app-arpbind，但在本项目中没有发现

这并不属于缺失，是lede中自己添加的，你有需要的话可以自行添加，本库主要是同步op官方的软件源

**Comment by f1owkang** [comment]
> > > 那是上游软件源问题，暂时只能本地修改
> > 
> > 
> > 感谢回复，我编译的时候观察到似乎软件包有缺失，例如在lede中有luci-app-arpbind，但在本项目中没有发现
> 
> 这并不属于缺失，是lede中自己添加的，你有需要的话可以自行添加，本库主要是同步op官方的软件源

十分感谢，我稍后尝试自行添加软件包
