### ISSUE TITLE
openwrt编译ffmpeg Makefile文件中添加libx264依赖，Libraries中找不到libx264问题

### ISSUE THREAD

**Issue by yonggedebaqi** [breeze303/openwrt-6.x#9]
openwrt编译ffmpeg Makefile文件中添加libx264依赖，Libraries中找不到libx264是为什么问题？lede源码可以在Libraries中选择libx264

**Comment by breeze303** [comment]
貌似官方并没有这个依赖，你可以移植过去

**Comment by yonggedebaqi** [comment]
官方有的，使用都没有./scripts/feeds install libx264都没有用

**Comment by breeze303** [comment]
https://github.com/openwrt/packages/blob/70c27beb0951e29bd51b161a9179973612826d87/libs/libx264/Makefile#L60 你需要按照mk里写的依赖去打开一些选项才会出现

**Comment by yonggedebaqi** [comment]
谢谢你！！~解决了
make menuconfig
进入
Global build settings  --->
选中
[*] Compile with support for patented functionality 

在
Libraries  --->
就可以选择libx264 libx265了
<*> libx264...................................... H264/AVC free codec library 
<*> libx265..................................... H265/HEVC free codec library
